objects: geticon getnetwork media-image ewwstartup

geticon: geticon.c
	gcc -o  geticon geticon.c

getnetwork: getnetwork.c
	gcc -o getnetwork getnetwork.c

media-image: media-image.c
	gcc -o media-image media-image.c

ewwstartup: ewwstartup.c
	gcc -o ewwstartup ewwstartup.c
