objects: getstats geticon getnetwork spotify-image spotify-check ewwstartup ewwtoggle

getstats: getstats.c
	gcc -lm -o getstats getstats.c

geticon: geticon.c
	gcc -o  geticon geticon.c

getnetwork: getnetwork.c
	gcc -o getnetwork getnetwork.c

spotify-image: spotify-image.c
	gcc -o spotify-image spotify-image.c

spotify-check: spotify-check.c
	gcc -o spotify-check spotify-check.c

ewwstartup: ewwstartup.c
	gcc -o ewwstartup ewwstartup.c

ewwtoggle: ewwtoggle.c
	gcc -o ewwtoggle ewwtoggle.c
